apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo
  name: postgres-data-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
