apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: todo
  name: todo-search-service
  labels:
    todo-app-deployment: todo-search-service
spec:
  replicas: 2
  selector:
      matchLabels:
        todo-app-pod: todo-search-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        todo-app-pod: todo-search-service
    spec:
      restartPolicy: Always
      initContainers:
      - name: init-elastic
        image: busybox
        command: ['sh', '-c', 'until nslookup todo-elastic; do echo waiting for ElasticSearch; sleep 2; done;']
      containers:
      - name: todo-search-service
        image: gravitonian/todo-search-service:1.0
        envFrom:
          - configMapRef:
              name: todo-config
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "134217728"
