apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: todo-rabbitmq-management
  labels:
    todo-app-service: todo-rabbitmq-management
spec:
  type: NodePort
  selector:
    todo-app-pod: todo-rabbitmq
  ports:
  - name: http
    port: 8081
    targetPort: 15672
